export const PAYLOAD_SCHEMA_VERSION = 7
export const CACHE_TTL_MS = 6 * 60 * 60 * 1000
export const MIN_HEALTHY_ROAD_CANDIDATES = 40
export const MIN_HEALTHY_BUILDING_CANDIDATES = 40
export const MIN_HEALTHY_CONTEXT_CANDIDATES = 5
